-- WebLoom Supabase schema
create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text unique,
  is_anonymous boolean not null default false,
  display_name text,
  settings jsonb not null default '{"capture_mode":"standard","export_format":"zip","project_naming":"hostname"}'::jsonb,
  role text not null default 'user' check (role in ('user','owner')),
  plan text not null default 'free' check (plan in ('free','pro')),
  free_capture_used boolean not null default false,
  stripe_customer_id text unique,
  stripe_subscription_id text unique,
  subscription_status text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles add column if not exists is_anonymous boolean not null default false;
alter table public.profiles add column if not exists display_name text;
alter table public.profiles add column if not exists settings jsonb not null default '{"capture_mode":"standard","export_format":"zip","project_naming":"hostname"}'::jsonb;

create table if not exists public.projects (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  source_url text not null,
  hostname text,
  status text not null default 'queued' check (status in ('queued','running','done','error')),
  engine text not null default 'webloom',
  file_count integer not null default 0,
  byte_count bigint not null default 0,
  failed_count integer not null default 0,
  preview_path text,
  archive_path text,
  error text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  finished_at timestamptz
);

create table if not exists public.free_trial_claims (
  trial_key text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  network_key text,
  claimed_at timestamptz not null default now()
);

create table if not exists public.usage_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  project_id uuid references public.projects(id) on delete set null,
  kind text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists projects_user_created_idx on public.projects(user_id, created_at desc);
create index if not exists usage_user_created_idx on public.usage_events(user_id, created_at desc);
create index if not exists free_trial_claims_user_idx on public.free_trial_claims(user_id);
create index if not exists free_trial_claims_network_idx on public.free_trial_claims(network_key, claimed_at desc);

alter table public.profiles enable row level security;
alter table public.projects enable row level security;
alter table public.free_trial_claims enable row level security;
alter table public.usage_events enable row level security;

drop policy if exists "profiles select own" on public.profiles;
create policy "profiles select own" on public.profiles
for select to authenticated
using ((select auth.uid()) = id);

drop policy if exists "profiles update own" on public.profiles;
create policy "profiles update own" on public.profiles
for update to authenticated
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id);

drop policy if exists "projects select own" on public.projects;
create policy "projects select own" on public.projects
for select to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "projects insert own" on public.projects;
create policy "projects insert own" on public.projects
for insert to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "projects update own" on public.projects;
create policy "projects update own" on public.projects
for update to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "projects delete own" on public.projects;
create policy "projects delete own" on public.projects
for delete to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "free trial claims own rows" on public.free_trial_claims;
create policy "free trial claims own rows" on public.free_trial_claims
for select to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "usage select own" on public.usage_events;
create policy "usage select own" on public.usage_events
for select to authenticated
using ((select auth.uid()) = user_id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, email, is_anonymous)
  values (new.id, nullif(new.email, ''), coalesce(new.is_anonymous, false))
  on conflict (id) do update
    set email = excluded.email,
        is_anonymous = excluded.is_anonymous,
        updated_at = now();
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert or update of email, is_anonymous on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.consume_capture_entitlement(
  p_trial_key text,
  p_network_key text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  p public.profiles%rowtype;
  existing_user uuid;
  recent_network_claims integer;
begin
  if v_user is null then
    raise exception 'authentication_required';
  end if;

  select * into p from public.profiles where id = v_user for update;
  if not found then
    raise exception 'profile_not_found';
  end if;

  if p.role = 'owner' then
    return jsonb_build_object('allowed', true, 'reason', 'owner', 'plan', 'owner');
  end if;

  if p.plan = 'pro' and coalesce(p.subscription_status,'') in ('active','trialing') then
    return jsonb_build_object('allowed', true, 'reason', 'pro', 'plan', 'pro');
  end if;

  if p.free_capture_used then
    return jsonb_build_object('allowed', false, 'reason', 'upgrade_required', 'plan', 'free');
  end if;

  if p_trial_key is null or length(p_trial_key) < 24 then
    return jsonb_build_object('allowed', false, 'reason', 'trial_key_required', 'plan', 'free');
  end if;

  select user_id into existing_user
  from public.free_trial_claims
  where trial_key = p_trial_key;

  if existing_user is not null and existing_user <> v_user then
    return jsonb_build_object('allowed', false, 'reason', 'free_device_used', 'plan', 'free');
  end if;

  if p_network_key is not null and length(p_network_key) >= 24 then
    select count(*) into recent_network_claims
    from public.free_trial_claims
    where network_key = p_network_key
      and claimed_at > now() - interval '24 hours'
      and user_id <> v_user;

    if recent_network_claims >= 3 then
      return jsonb_build_object('allowed', false, 'reason', 'free_network_rate_limited', 'plan', 'free');
    end if;
  end if;

  insert into public.free_trial_claims (trial_key, user_id, network_key)
  values (p_trial_key, v_user, p_network_key)
  on conflict (trial_key) do nothing;

  update public.profiles
  set free_capture_used = true, updated_at = now()
  where id = v_user;

  insert into public.usage_events (user_id, kind, metadata)
  values (
    v_user,
    'free_capture_claimed',
    jsonb_build_object('trial_key', p_trial_key, 'network_key', p_network_key)
  );

  return jsonb_build_object('allowed', true, 'reason', 'free', 'plan', 'free');
end;
$$;

revoke all on function public.consume_capture_entitlement(text,text) from public;
grant execute on function public.consume_capture_entitlement(text,text) to authenticated;

create or replace function public.restore_free_capture(p_trial_key text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
begin
  if v_user is null then
    raise exception 'authentication_required';
  end if;

  delete from public.free_trial_claims
  where trial_key = p_trial_key and user_id = v_user;

  update public.profiles
  set free_capture_used = false, updated_at = now()
  where id = v_user and role = 'user' and plan = 'free';
end;
$$;

revoke all on function public.restore_free_capture(text) from public;
grant execute on function public.restore_free_capture(text) to authenticated;

create or replace function public.set_subscription_state(
  p_user uuid,
  p_customer text,
  p_subscription text,
  p_status text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.profiles
  set stripe_customer_id = coalesce(p_customer, stripe_customer_id),
      stripe_subscription_id = coalesce(p_subscription, stripe_subscription_id),
      subscription_status = p_status,
      plan = case when p_status in ('active','trialing') then 'pro' else 'free' end,
      updated_at = now()
  where id = p_user;
end;
$$;

revoke all on function public.set_subscription_state(uuid,text,text,text) from public;
grant execute on function public.set_subscription_state(uuid,text,text,text) to service_role;

insert into storage.buckets (id, name, public, file_size_limit)
values ('webloom-projects', 'webloom-projects', false, 104857600)
on conflict (id) do update
set public = false,
    file_size_limit = excluded.file_size_limit;

drop policy if exists "webloom storage read own" on storage.objects;
create policy "webloom storage read own"
on storage.objects for select to authenticated
using (
  bucket_id = 'webloom-projects'
  and (storage.foldername(name))[1] = 'projects'
  and (storage.foldername(name))[2] = (select auth.uid())::text
);

drop policy if exists "webloom storage insert own" on storage.objects;
create policy "webloom storage insert own"
on storage.objects for insert to authenticated
with check (
  bucket_id = 'webloom-projects'
  and (storage.foldername(name))[1] = 'projects'
  and (storage.foldername(name))[2] = (select auth.uid())::text
);

drop policy if exists "webloom storage update own" on storage.objects;
create policy "webloom storage update own"
on storage.objects for update to authenticated
using (
  bucket_id = 'webloom-projects'
  and (storage.foldername(name))[1] = 'projects'
  and (storage.foldername(name))[2] = (select auth.uid())::text
)
with check (
  bucket_id = 'webloom-projects'
  and (storage.foldername(name))[1] = 'projects'
  and (storage.foldername(name))[2] = (select auth.uid())::text
);

drop policy if exists "webloom storage delete own" on storage.objects;
create policy "webloom storage delete own"
on storage.objects for delete to authenticated
using (
  bucket_id = 'webloom-projects'
  and (storage.foldername(name))[1] = 'projects'
  and (storage.foldername(name))[2] = (select auth.uid())::text
);
